### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by duraki** [NorthwaveNL/fridax#14]
I have the same issue as #13 and I think it's tied to your toolset rather then `node-gyp`. You need to include `binding.gyp` file in your project directory (a sort of Makefile). Tried on two environments (Host - MacOS Catalina, Guest - Kali Linux)

```
┌──(kali㉿kali)-[/tmp/fridax]
└─$ pwd                                                                                                       130 ⨯ 1 ⚙
/tmp/fridax
                                                                                                                        
┌──(kali㉿kali)-[/tmp/fridax]
└─$ npm --version                                                                                                   1 ⚙
7.0.3

┌──(kali㉿kali)-[/tmp/fridax]
└─$ rm -rf node_modules package-lock.json && npm i                                                                  1 ⚙
npm ERR! code 1
npm ERR! path /tmp/fridax/node_modules/frida
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.0.0
npm ERR! gyp info using node@12.19.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.4 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/tmp/fridax/node_modules/frida/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/tmp/fridax/node_modules/frida',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: /tmp/fridax/node_modules/frida) while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:354:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! System Linux 5.7.0-kali1-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /tmp/fridax/node_modules/frida
npm ERR! gyp ERR! node -v v12.19.0
npm ERR! gyp ERR! node-gyp -v v7.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2020-12-01T12_42_46_721Z-debug.log
```

**Comment by duraki** [comment]
Figured out this due to https://github.com/frida/frida-node/issues/42#issuecomment-496709766. Only up to Node v12 is supported. Hopefully Ole will push some updates to the repo.

**Comment by duraki** [comment]
Well, that didn't help. Now the `npm i` yields the following:

```
$ × rm -rf node_modules && npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> frida@12.11.18 install /Users/me/util/re/fridax/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.20.0 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /Users/me/util/re/fridax/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node@12/12.20.0/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/util/re/fridax/node_modules/frida
gyp ERR! node -v v12.20.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.11.18 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@12.11.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-12-01T13_52_04_348Z-debug.log
```

**Comment by tijme** [comment]
Hi @duraki, I think this is a node-gyp issue. Check [this](https://github.com/nodejs/node-gyp/issues/233) for more info and possible solutions for your environment.

**Comment by lNATl** [comment]
> Well, that didn't help. Now the `npm i` yields the following:
> 
> ```
> $ × rm -rf node_modules && npm i
> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
> 
> > frida@12.11.18 install /Users/me/util/re/fridax/node_modules/frida
> > prebuild-install || node-gyp rebuild
> 
> prebuild-install WARN install No prebuilt binaries found (target=12.20.0 runtime=node arch=x64 libc= platform=darwin)
> gyp: binding.gyp not found (cwd: /Users/me/util/re/fridax/node_modules/frida) while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
> gyp ERR! System Darwin 19.6.0
> gyp ERR! command "/usr/local/Cellar/node@12/12.20.0/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/me/util/re/fridax/node_modules/frida
> gyp ERR! node -v v12.20.0
> gyp ERR! node-gyp -v v7.1.2
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! frida@12.11.18 install: `prebuild-install || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the frida@12.11.18 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/me/.npm/_logs/2020-12-01T13_52_04_348Z-debug.log
> ```

I have also received similar issues on windows 10 x64.
Windows_NT 10.0.19043
node v18.12.1
node-gyp v9.3.1
Python version 3.10.5
msvs_version = "2017"
